### ISSUE TITLE
Some conversions are incorrect

### ISSUE THREAD

**Issue by hcarty** [andrenth/ocaml-stdint#8]
On a 64bit OCaml 4.02.3, latest stdint from opam:

``` ocaml
(* Testing in the toplevel *)
# Stdint.Uint32.to_int @@ Stdint.Uint32.of_int 0xFFFFFFFF;;
- : int = -1
```

but I would have expected `4294967295`.

The conversion to `Int64.t` does work properly:

``` ocaml
# Stdint.Uint32.to_int64 @@ Stdint.Uint32.of_int 0xFFFFFFFF;;
- : int64 = 4294967295L
```

**Comment by andrenth** [comment]
I'm not really sure to be honest. Current behavior mirrors C:

```C
int
main() {
    int x = 0xFFFFFFFF;
    printf("%d, %ld\n", (int)((uint32_t)x), (int64_t)((uint32_t)x)); // -1, 4294967295
}
```

**Comment by hcarty** [comment]
On my work machine (64bit OSX) this makes sense because `int` is still 32bit, while it's 64(ish) bits in OCaml:

```c
#include <stdio.h>
#include <inttypes.h>

int main() {
    int xi = 0xFFFFFFFF;
    uint32_t xu32 = 0xFFFFFFFF;
    int64_t x64 = 0xFFFFFFFF;
    printf("xi: %d, xu32: %" PRIu32 ", x64: %" PRId64"\n", xi, xu32, x64);
    printf("bytes: %zu\n", sizeof(xi));
}
```

Output:
```
$ cc m.c
$ ./a.out 
xi: -1, xu32: 4294967295, x64: 4294967295
bytes: 4
```

**Comment by andrenth** [comment]
Indeed. I'll try to fix it today.

**Comment by mwweissmann** [comment]
Version 0.3.0 does indeed show this incorrect behavior on 64-bit Linux, too. The most recent code works correctly for me (on 64 Bit Linux).
On 32-bit Linux this of course fails to compile because 0xFFFFFFFF does not fit into the 31-bit ```int```.

**Comment by andrenth** [comment]
Hm I was sure I had replied to this issue... I believe the latest commits to master (specifically 9f468e1) fix this issue.

**Comment by hcarty** [comment]
I won't be able to test this for another week or two, but thank you for working on this!

**Comment by oandrieu** [comment]
> Hm I was sure I had replied to this issue... I believe the latest commits to master (specifically 9f468e1) fix this issue.

this commit doesn't look right. `long` is still not the appropriate type on some platforms (on 64 bits windows, `long` is 32 bits).

You probably should just use the OCaml macros. Instead of: `Val_int((long)Int16_val(v))`, use `Val_long(Int16_val(v))`. The `Val_long` macro will do the cast — not always to `long` as it happens.

**Comment by andrenth** [comment]
Hi Olivier.

I didn't know that about Windows... Do you think simply removing all casts to `long` would be ok? It builds fine here without them and all the tests pass, but I don't have a way to test on other architectures.

**Comment by oandrieu** [comment]
> Do you think simply removing all casts to long would be ok?

Yes. If you want to keep an explicit cast, it should be a cast to `intnat`, not `long`.

**Comment by hcarty** [comment]
Thank you @yallop!
